//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace regMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class caja
    {
        [Display(Name = "Dinero venta")]
        public Nullable<double> dinero_final { get; set; }

        [Display(Name = "Día de venta")]
        public Nullable<System.DateTime> fecha_dia { get; set; }

        [Display(Name = "Mes venta")]
        public Nullable<System.DateTime> fecha_mes { get; set; }

        [Display(Name = "Año venta")]
        public Nullable<System.DateTime> fecha_año { get; set; }

        [Display(Name = "Cantidad de venta")]
        public Nullable<int> cantidad_vendida { get; set; }
        public int id_caja { get; set; }

        [Display(Name = "Nombre")]
        public string nombre { get; set; }

        [Display(Name = "Código")]
        public string cod_prod { get; set; }
        public string cedula { get; set; }
    }
}
