//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace regMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class economia
    {
        [DataType(DataType.Currency)]
        public Nullable<double> dinero_total { get; set; }

        public int id_economia { get; set; }

        [DataType(DataType.Currency)]
        public Nullable<double> tot_money_bodega { get; set; }

        [DataType(DataType.Currency)]
        public Nullable<double> tot_money_mostrador { get; set; }

        public Nullable<int> id_bodega { get; set; }
        public string cod_prod { get; set; }
    
        public virtual bodega bodega { get; set; }
    }
}
